name: DotnetCore
#name: CI

on:
  workflow_dispatch: #Trigger de onde vai rodar.

jobs: #Agregam vários trabalhos de execuções dentro do pipeline.
  build: # É o 1º Job dentro do pipeline (Pode ter outro nome, o que mais fizer sentido).
    runs-on: ubuntu-latest #Onde roda o pipeline no sistema operacional Matrix
    
    #strategy: #A estratégica de implantação de a de Matrix
      #matrix:
        #node_version: ['8', '10', '12']
        #os: [ubuntu-latest, windows-latest, macOS-latest]
        #[ubuntu-latest, windows-latest, macOS-latest] Versões do sistema operacional.


    steps: #Passos.
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        #run: echo Hello, world!
        uses: actions/setup-dotnet@v1
        with: 
         dotnet-version: 5.0.100

      #- name: Run a multi-line script
      - name: Install dependecies
       # run: | #Linha de comando
        #  echo Add other actions to build,
       #   echo test, and deploy your project.
        run: dotnet restore
       
      - name: Build
        run: dotnet build --configuration Release --no-restore
       
      - name: Test
        run: dotnet test --no-restore --verbosity normal
       
      - name: Dotnet Publish
        run: dotnet publish --configuration Release -o ${{ github.workspace }}/demo
       
      - name: Upload Artifact
        uses: actions/upload-artifact@v1 
        with: 
                             name: app
                             path: ${{ github.workspace }}//demo
        
       
